version: 2.1
orbs:
  coveralls: coveralls/coveralls@x.y.z
jobs:
  run-test: 
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            pip install --user -r requirements.txt
      - run:
          name: Run Unit Tests
          command: |
            pip install --user pytest-html
            pytest --junitxml=test-report/junit.xml --html=test-report/pytest_report.html
      - run:
          name: Install and Make
          command: 'npm install && make test-coverage'

      - coveralls/upload
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
workflows:
  sample:  
    jobs:
      - run-test