version: 2.1
jobs:
  run-test: 
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            pip install --user requirements.txt
      - run:
          name: Run Unit Tests
          command: |
            pytest --junitxml=test-report/junit.xml --html=test-report/pytest_report.html --self-contained-html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
workflows:
  sample:  
    jobs:
      - run-test