version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  run-test: 
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            pip install --user -r requirements.txt
      - run:
          name: Run Unit Tests
          command: |
            pip install --user pytest-html
            pytest --junitxml=test-report/junit.xml --html=test-report/pytest_report.html
      - run:
          name: pip install --user coverage
          command: sh -c 'cd ./flask_app/ && coverage run -m --source=app unittest discover test && coverage report'
      - run:
          name: Install coveralls
          command: pip install coveralls
      - run:
          name: Uploading coverage to coveralls
          command: coveralls --lcov-file /-yummy_recipes_frontend-/flask_app/coverage.lcov
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
          
workflows:
  sample:  
    jobs:
      - run-test